name: Deploy to Hostinger

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build project
        run: |
          cd arthur-guerin-portfolio
          npm install
          npm install --save-dev @babel/plugin-proposal-private-property-in-object
          npm run build

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH Host Key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 65002 213.130.145.114 >> ~/.ssh/known_hosts

      - name: Deploy to Hostinger
        env:
          HOSTINGER_USER: u903679210
          HOSTINGER_HOST: 213.130.145.114
          HOSTINGER_PORT: 65002
          PROJECT_DIR: domains/arthur-guerin.dev/public_html/VegasFolio/folio/build
        run: |

          ssh -tt -p $HOSTINGER_PORT $HOSTINGER_USER@$HOSTINGER_HOST << 'EOF'
            cd domains/arthur-guerin.dev/public_html/VegasFolio/folio/build

            cp * /

            
            exit
          EOF
