name: Deploy to Hostinger

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Hostinger
        env:
          HOSTINGER_USER: u903679210
          HOSTINGER_HOST: 213.130.145.114
          HOSTINGER_PORT: 65002
          PROJECT_DIR: /arthur-guerin-portfolio
        run: |
          ssh -tt u903679210@213.130.145.114 << 'EOF'
            cd $PROJECT_DIR
            git pull
            npm install
            npm run build
            pm2 restart all || npm run start
          EOF
